from datetime import date, timedelta
from calendar import monthrange


def get_weekends_date(start_date: date, end_date: date) -> list[date]:
    today = start_date
    weekends: list[date] = []
    while today != end_date:
        if today.weekday() >= 5:
            weekends.append(today)
        today += timedelta(1)
    return weekends



def get_skills() -> list[str]:
    return [
        "3D PRINTING CONCEPTS, DESIGN AND PRINTING",
        "Accounting",
        "Adobe Illustrator",
        "Adobe Indesign",
        "Adobe Photoshop",
        "Android Studio",
        "Angular",
        "AWS",
        "Azure",
        "BIM CONCEPTS WITH MEP AND PRODUCT DESIGN",
        "BIM FOR ARCHITECTURE",
        "BIM FOR CONSTRUCTION",
        "BIM FOR HIGHWAY ENGINEERING",
        "BIM FOR STRUCTURES",
        "Business Management",
        "Business operations and Strategy",
        "C++",
        "CakePHP",
        "Canva",
        "Cassandra",
        "Circuit Design",
        "Cloud access control",
        "CodeIgniter",
        "computer vision",
        "CSS",
        "D3.js",
        "Data encryption",
        "Data modeling",
        "Data visualization",
        "Database design",
        "Design with FPGA",
        "DevOps",
        "DHCP",
        "Digital Design",
        "Docker",
        "Economics",
        "Embedded Systems",
        "entrepreneurship",
        "Figma",
        "FilamentPHP",
        "Finance",
        "Firewall configuration",
        "Flutter",
        "Game design",
        "Game development",
        "Game engine",
        "Git",
        "Godot",
        "Google Cloud",
        "HTML",
        "Human Resource Management",
        "IaaS",
        "Indexing",
        "Intelligent Machines",
        "INTERIOR AND EXTERIOR DESIGN",
        "Inventory Management",
        "IoT",
        "Java",
        "JavaScript",
        "Keras",
        "Kotlin",
        "Kubernetes",
        "LAN",
        "Laravel",
        "Layout Design",
        "Machine learning",
        "Macro economics",
        "Management Information System",
        "Manufacturing",
        "Market Theory",
        "Marketing",
        "Micro economics",
        "MongoDB",
        "MySQL",
        "Natural language processing",
        "Network architecture",
        "Node.js",
        "NoSQL",
        "Objective-C",
        "Operations Management",
        "PaaS",
        "PHP",
        "Physical Design",
        "Planning & Control systems",
        "PostgreSQL",
        "Power BI",
        "PRODUCT DESIGN & 3D PRINTING",
        "PRODUCT DESIGN & MANUFACTURING",
        "Python",
        "PyTorch",
        "React",
        "React.js",
        "Risk management",
        "Ruby on Rails",
        "SaaS",
        "Sales & Marketing",
        "scikit-learn",
        "SEO",
        "SQL",
        "Statistical analysis",
        "Swift",
        "Tableau",
        "TCP/IP",
        "TensorFlow",
        "TypeScript",
        "UI/UX",
        "UX design",
        "Verification & Validations",
        "VLSI Design",
        "VPNs",
        "Vue.js",
        "WAN",
        "WordPress",
        "Xamarin",
        "Xcode",
    ]
